twoliter: use older workspace manifest if present
To minimize churn in the boilerplate around a project, accept the old
location for the cargo workspace covering the artifacts that buildsys
manages. Emit a warning in that case to encourage a move to the new
path.

To avoid ambiguity, refuse to build a project that has both files.

Signed-off-by: Ben Cressey <bcressey@amazon.com>

diff --git a/twoliter/embedded/Makefile.toml b/twoliter/embedded/Makefile.toml
--- a/twoliter/embedded/Makefile.toml
+++ b/twoliter/embedded/Makefile.toml
@@ -329,11 +329,10 @@ dependencies = ["setup"]
 script_runner = "bash"
 script = [
 '''
-if [ -f "${BUILDSYS_SOURCES_DIR}/Cargo.toml" ]; then
-  cargo fetch --locked --manifest-path "${BUILDSYS_SOURCES_DIR}/Cargo.toml"
-fi
-
-cargo fetch --locked --manifest-path "${BUILDSYS_ROOT_DIR}/Cargo.toml"
+for ws in sources variants .; do
+  [ -s "${BUILDSYS_ROOT_DIR}/${ws}/Cargo.toml" ] || continue
+  cargo fetch --locked --manifest-path "${BUILDSYS_ROOT_DIR}/${ws}/Cargo.toml"
+done
 
 chmod -R o+r ${CARGO_HOME}
 '''
@@ -744,10 +743,27 @@ dependencies = ["setup"]
 script_runner = "bash"
 script = [
 '''
+OLD_WS_MANIFEST="${BUILDSYS_ROOT_DIR}/variants/Cargo.toml"
+NEW_WS_MANIFEST="${BUILDSYS_ROOT_DIR}/Cargo.toml"
+if [ -s "${OLD_WS_MANIFEST}" ] && [ -s "${NEW_WS_MANIFEST}" ]; then
+  echo "Found two project workspaces: ${OLD_WS_MANIFEST} and ${NEW_WS_MANIFEST}.">&2
+  echo "This configuration is not supported.">&2
+  exit 1
+elif [ -s "${NEW_WS_MANIFEST}" ]; then
+  PROJECT_MANIFEST="${NEW_WS_MANIFEST}"
+elif [ -s "${OLD_WS_MANIFEST}" ]; then
+  echo "Found deprecated project workspace ${OLD_WS_MANIFEST}.">&2
+  echo "Please relocate it to ${NEW_WS_MANIFEST}.">&2
+  PROJECT_MANIFEST="${OLD_WS_MANIFEST}"
+else
+  echo "Could not find project workspace at ${NEW_WS_MANIFEST}. Please create it." >&2
+  exit 1
+fi
+
 rm -f "${BUILDSYS_CARGO_METADATA_PATH}"
 cargo metadata \
   --format-version 1 \
-  --manifest-path "${BUILDSYS_ROOT_DIR}/Cargo.toml" \
+  --manifest-path "${PROJECT_MANIFEST}" \
   --offline \
   --all-features \
   > "${BUILDSYS_CARGO_METADATA_PATH}"
@@ -1573,7 +1589,19 @@ rm -f ${BUILDSYS_TOOLS_DIR}/bin/*
 script_runner = "bash"
 script = [
 '''
-cargo clean --manifest-path "${BUILDSYS_ROOT_DIR}/Cargo.toml"
+# The workspace manifest could be the old one under variants, or the new one at
+# the project root.
+for ws in variants .; do
+  manifest="${BUILDSYS_ROOT_DIR}/${ws}/Cargo.toml"
+  [ -s "${manifest}" ] || continue
+  # The targets directory could be under variants, or at the root, for either of
+  # the possible workspace manifest locations.
+  for td in target variants/target ; do
+    targets="${BUILDSYS_ROOT_DIR}/${td}/${BUILDSYS_ARCH}"
+    [ -d "${targets}" ] || continue
+    CARGO_TARGET_DIR="${targets}" cargo clean --manifest-path "${manifest}"
+  done
+done
 '''
 ]
 
